### ISSUE TITLE
Merge Sydney's Instruction changes for muse-io

### ISSUE THREAD

**Issue by jdpigeon** [bcimontreal/bci_workshop#11]

**Comment by micuat** [comment]
@jdpigeon @syswsi needs clarification about conda/pip stuff

**Comment by micuat** [comment]
sydney's instruction is here https://github.com/syswsi/BCI-Workshop-new-instructions/blob/master/Instructions.md

**Comment by micuat** [comment]
we should add that if you're running python from command line you should add -u option to disable stdout buffering (`python -u exercise_02.py`)

**Comment by jdpigeon** [comment]
I just copied in Syd's instructions. 

@micuat, for the stdout buffering instruction, does that apply to all users or just those using muse-io?

**Comment by micuat** [comment]
Great! I think the buffering issue rather depends on the python platform. I
saw this problem with windows / anaconda but not sure about osx and Linux.

**Comment by micuat** [comment]
ok I edited the instructions a bit.

one more thing, I think we should split the instructions as it is getting longer. I found some people were confused by muse-io/muse-lsl at the workshop in montreal so maybe we should make 2 versions for old muse and ble muse?

**Comment by micuat** [comment]
i think the current instruction is good so i'm closing this issue
