### ISSUE TITLE
Muse SDK link broken

### ISSUE THREAD

**Issue by micuat** [bcimontreal/bci_workshop#2]
In the `INSTRUCTIONS.md`,

> To install the SDK, download and execute the Muse SDK Tools 3.4.1 installer for Windows.

When open the link, it is automatically redirected to http://developer.choosemuse.com. Although it is not apparent, _Research Tools_ > (Windows Logo) _Download_ link is the SDK 3.4.1.

**Comment by rcassani** [comment]
Thanks a lot for the info, I'll update it

**Comment by FerEph** [comment]
Do you want the insight to add to mules?

Sent from Yahoo Mail on Android 

  On Tue, Nov 10, 2015 at 10:24, Raymundo Cassaninotifications@github.com wrote:  
Thanks a lot for the info, I'll update it

**Comment by rcassani** [comment]
Muse SDK links are updated
