### ISSUE TITLE
manually set muse-io arguments

### ISSUE THREAD

**Issue by micuat** [bcimontreal/bci_workshop#3]
Hi Ray,
Is it possible to manually set command line arguments for muse-io? For example, this enables to get blink events in other apps (python, processing, etc). For now, I found a workaround: first, launch muse-io with

```
$ muse-io --device Muse-XXXX --osc 'osc.tcp://localhost:5000' --osc-bp-urls 'osc.udp://localhost:12000'
```

then launch MuLES, start device and close the command prompt opend by MuLES.

**Comment by rcassani** [comment]
Hey,
That function is not explicitly implemented. 
However the command created to call muse-io.exe takes parameters from the `çonfig.ini` as follows

`/muse-io.exe --preset PRESET --device BTNAME --osc osc.tcp://localhost:OSCPORT`

Then to replicate the set of arguments you want you could try to change the value of 

`OSCPORT` in the MuLES `config.ini` file from: `5000`  to 
`5000 --osc-bp-urls 'osc.udp://localhost:12000'`

That should make the trick

**Comment by micuat** [comment]
closing this as the current master doesn't depend on mules anymore
