### ISSUE TITLE
Data is out of bounds in lsl-viewer when streaming from muse-io

### ISSUE THREAD

**Issue by jdpigeon** [bcimontreal/bci_workshop#9]
https://neurotechx.slack.com/files/U08SY292B/F8QDU3BK5/image.png

Probably due to filtering being handled differently

**Comment by micuat** [comment]
I confirm that toggle filter (pressing 'd') fixed the bias issue. maybe add this to the documentation and close the issue? @jdpigeon @syswsi

**Comment by micuat** [comment]
https://github.com/NeuroTechX/bci-workshop/commit/4d32c3bd94a079633255bfd9fdcefdb742241bfd
